# To troubleshoot and get more log info enable ldap debug logging in grafana.ini
#[log]
#filters = ldap:debug

[[servers]]
{% for server in ekara_configuration_params.params.grafana.ldap.servers %}
{% for k,v in server.items() %}
{{ k }} = {{ v | to_nice_json }}
{% endfor %}
{% endfor %}

# Specify names of the ldap attributes your ldap uses
[servers.attributes]
{% for k,v in ekara_configuration_params.params.grafana.ldap.servers_attributes.items() %}
{{ k }} = {{ v | to_nice_json }}
{% endfor %}

# Map ldap groups to grafana org roles
{% for group in ekara_configuration_params.params.grafana.ldap.servers_group_mappings %}
[[servers.group_mappings]]
{% for k,v in group.items() %}
{{ k }} = {{ v | to_nice_json }}
{% endfor %}

{% endfor %}
