---
global:
  # How frequently to scrape targets by default.
  scrape_interval: 15s

  # How long until a scrape request times out.
  scrape_timeout: 15s

  # How frequently to evaluate rules.
  evaluation_interval: 15s

  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: ekara

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
- /opt/ekara/rules/*.rules

# A list of scrape configurations.
scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'cadvisor'
  scrape_interval: 5s
  dns_sd_configs:
  - names:
    - 'tasks.cadvisor'
    type: 'A'
    port: 8080

- job_name: 'node-exporter'
  scrape_interval: 5s
  dns_sd_configs:
  - names:
    - 'tasks.node-exporter'
    type: 'A'
    port: 9100

- job_name: 'pushgateway'
  scrape_interval: 5s
  honor_labels: true
  dns_sd_configs:
  - names:
    - 'tasks.pushgateway'
    type: 'A'
    port: 9091

- job_name: 'alertmanager'
  scrape_interval: 5s
  dns_sd_configs:
  - names:
    - 'tasks.alertmanager'
    type: 'A'
    port: 9093

# Alerting specifies settings related to the Alertmanager.
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
